// Date: 1/15/2017 4:35:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cubic_control.hnm.Entity.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCamera extends ModelBase
{
  //fields
    ModelRenderer CameraBase;
    ModelRenderer CameraExtension;
    ModelRenderer CameraStick;
    ModelRenderer CameraLense;
    ModelRenderer CameraFlash;
  
  public ModelCamera()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      CameraBase = new ModelRenderer(this, 0, 0);
      CameraBase.addBox(0F, 0F, 0F, 3, 3, 4);
      CameraBase.setRotationPoint(-1.5F, 12F, 4F);
      CameraBase.setTextureSize(64, 32);
      CameraBase.mirror = true;
      setRotation(CameraBase, 0F, 0F, 0F);
      CameraExtension = new ModelRenderer(this, 14, 0);
      CameraExtension.addBox(-1.5F, 0F, -2F, 3, 3, 2);
      CameraExtension.setRotationPoint(0F, 12F, 4F);
      CameraExtension.setTextureSize(64, 32);
      CameraExtension.mirror = true;
      setRotation(CameraExtension, 0.2617994F, 0F, 0F);
      CameraStick = new ModelRenderer(this, 24, 0);
      CameraStick.addBox(-0.5F, 1F, -6F, 1, 1, 2);
      CameraStick.setRotationPoint(0F, 12F, 7F);
      CameraStick.setTextureSize(64, 32);
      CameraStick.mirror = true;
      setRotation(CameraStick, 0F, 0F, 0F);
      CameraLense = new ModelRenderer(this, 30, 0);
      CameraLense.addBox(0F, 0.5F, 0F, 2, 2, 2);
      CameraLense.setRotationPoint(-1F, 12F, -1F);
      CameraLense.setTextureSize(64, 32);
      CameraLense.mirror = true;
      setRotation(CameraLense, 0F, 0F, 0F);
      CameraFlash = new ModelRenderer(this, 38, 0);
      CameraFlash.addBox(0F, -2F, 0F, 1, 2, 1);
      CameraFlash.setRotationPoint(-1F, 12F, 5F);
      CameraFlash.setTextureSize(64, 32);
      CameraFlash.mirror = true;
      setRotation(CameraFlash, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    CameraBase.render(f5);
    CameraExtension.render(f5);
    CameraStick.render(f5);
    CameraLense.render(f5);
    CameraFlash.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
