// Date: 1/8/2017 5:26:35 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cubic_control.hnm.Entity.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPadlockBlue extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer BaseExtention1;
    ModelRenderer BaseExtention2;
    ModelRenderer LockArmLeft;
    ModelRenderer LockArmRight;
    ModelRenderer LockArmMiddle;
  
  public ModelPadlockBlue()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(3F, 20F, 6F, 4, 2, 2);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      BaseExtention1 = new ModelRenderer(this, 12, 0);
      BaseExtention1.addBox(3.5F, 21.5F, 6F, 3, 1, 2);
      BaseExtention1.setRotationPoint(0F, 0F, 0F);
      BaseExtention1.setTextureSize(64, 32);
      BaseExtention1.mirror = true;
      setRotation(BaseExtention1, 0F, 0F, 0F);
      BaseExtention2 = new ModelRenderer(this, 22, 0);
      BaseExtention2.addBox(4F, 22F, 6F, 2, 1, 2);
      BaseExtention2.setRotationPoint(0F, 0F, 0F);
      BaseExtention2.setTextureSize(64, 32);
      BaseExtention2.mirror = true;
      setRotation(BaseExtention2, 0F, 0F, 0F);
      LockArmLeft = new ModelRenderer(this, 30, 0);
      LockArmLeft.addBox(3.5F, 16F, 6.5F, 1, 4, 1);
      LockArmLeft.setRotationPoint(0F, 0F, 0F);
      LockArmLeft.setTextureSize(64, 32);
      LockArmLeft.mirror = true;
      setRotation(LockArmLeft, 0F, 0F, 0F);
      LockArmRight = new ModelRenderer(this, 34, 0);
      LockArmRight.addBox(5.5F, 16F, 6.5F, 1, 4, 1);
      LockArmRight.setRotationPoint(0F, 0F, 0F);
      LockArmRight.setTextureSize(64, 32);
      LockArmRight.mirror = true;
      setRotation(LockArmRight, 0F, 0F, 0F);
      LockArmMiddle = new ModelRenderer(this, 38, 0);
      LockArmMiddle.addBox(4.5F, 16F, 6.5F, 1, 1, 1);
      LockArmMiddle.setRotationPoint(0F, 0F, 0F);
      LockArmMiddle.setTextureSize(64, 32);
      LockArmMiddle.mirror = true;
      setRotation(LockArmMiddle, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    BaseExtention1.render(f5);
    BaseExtention2.render(f5);
    LockArmLeft.render(f5);
    LockArmRight.render(f5);
    LockArmMiddle.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
