// Date: 12/31/2016 5:25:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cubic_control.hnm.Entity.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGrave extends ModelBase
{
  //fields
    ModelRenderer shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
  
  public ModelGrave()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      shape1 = new ModelRenderer(this, 0, 0);
      shape1.addBox(0F, 0F, 0F, 3, 31, 1);
      shape1.setRotationPoint(-1.5F, -7F, -7F);
      shape1.setTextureSize(64, 32);
      shape1.mirror = true;
      setRotation(shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 8, 0);
      Shape2.addBox(0F, 0F, 0F, 14, 3, 1);
      Shape2.setRotationPoint(-7F, -2F, -8F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 38, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 5, 2);
      Shape3.setRotationPoint(1.5F, -2.5F, -8.2F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.7853982F);
      Shape4 = new ModelRenderer(this, 44, 0);
      Shape4.addBox(0F, 0F, 0F, 1, 5, 2);
      Shape4.setRotationPoint(-2F, -2F, -8.1F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, -0.7853982F);
      Shape5 = new ModelRenderer(this, 50, 0);
      Shape5.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape5.setRotationPoint(1.5F, -2.5F, -6.9F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0.7853982F);
      Shape6 = new ModelRenderer(this, 54, 0);
      Shape6.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape6.setRotationPoint(-2F, -2F, -6.8F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, -0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
