// Date: 1/12/2017 11:38:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.cubic_control.hnm.Entity.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGallonOfMilk extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer BaseExtension;
    ModelRenderer HandleStart;
    ModelRenderer HandleMiddle;
    ModelRenderer HandleEnd;
    ModelRenderer Lid;
  
  public ModelGallonOfMilk()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base = new ModelRenderer(this, 0, 0);
      Base.addBox(-4F, 16F, -2F, 9, 8, 5);
      Base.setRotationPoint(0F, 0F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      BaseExtension = new ModelRenderer(this, 28, 0);
      BaseExtension.addBox(-4F, 9F, -2F, 4, 7, 5);
      BaseExtension.setRotationPoint(0F, 0F, 0F);
      BaseExtension.setTextureSize(64, 32);
      BaseExtension.mirror = true;
      setRotation(BaseExtension, 0F, 0F, 0F);
      HandleStart = new ModelRenderer(this, 46, 0);
      HandleStart.addBox(4F, 14F, -1.5F, 1, 2, 4);
      HandleStart.setRotationPoint(0F, 0F, 0F);
      HandleStart.setTextureSize(64, 32);
      HandleStart.mirror = true;
      setRotation(HandleStart, 0F, 0F, 0F);
      HandleMiddle = new ModelRenderer(this, 0, 23);
      HandleMiddle.addBox(-7F, 8F, -1.5F, 1, 5, 4);
      HandleMiddle.setRotationPoint(0F, 0F, 0F);
      HandleMiddle.setTextureSize(64, 32);
      HandleMiddle.mirror = true;
      setRotation(HandleMiddle, 0F, 0F, -0.7853982F);
      HandleEnd = new ModelRenderer(this, 10, 27);
      HandleEnd.addBox(0F, 10F, -1.5F, 1, 1, 4);
      HandleEnd.setRotationPoint(0F, 0F, 0F);
      HandleEnd.setTextureSize(64, 32);
      HandleEnd.mirror = true;
      setRotation(HandleEnd, 0F, 0F, 0F);
      Lid = new ModelRenderer(this, 20, 29);
      Lid.addBox(-3F, 8F, -0.5F, 2, 1, 2);
      Lid.setRotationPoint(0F, 0F, 0F);
      Lid.setTextureSize(64, 32);
      Lid.mirror = true;
      setRotation(Lid, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    BaseExtension.render(f5);
    HandleStart.render(f5);
    HandleMiddle.render(f5);
    HandleEnd.render(f5);
    Lid.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
